<?php

namespace AppBundle\Repository;

/**
 * DevisProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DevisProduitRepository extends \Doctrine\ORM\EntityRepository
{
}
