<?php

namespace AppBundle\Repository;

/**
 * InfoMailingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoMailingRepository extends \Doctrine\ORM\EntityRepository
{
}
