<?php

namespace AppBundle\Repository;

/**
 * TicketClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketClientRepository extends \Doctrine\ORM\EntityRepository
{
}
